# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15R3D0CJfgX-DY1q3Rg1BDlCjhBc1redB
"""

!pip install transformers datasets tqdm accelerate

from transformers import GPT2LMHeadModel, GPT2TokenizerFast
from datasets import load_dataset
import torch
from tqdm import tqdm
import math

device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")
model = GPT2LMHeadModel.from_pretrained("gpt2").to(device)
model.eval()

dataset = load_dataset("commonsense_qa")
data = dataset["validation"]  # ~1221 samples

def option_loglikelihood(question, option):
    prompt = question.strip() + "\nAnswer: " + option.strip()

    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    input_ids = inputs["input_ids"]

    # Shift for causal LM
    with torch.no_grad():
        outputs = model(input_ids, labels=input_ids)
        # loss is average negative log-likelihood over all tokens
        neg_log_likelihood = outputs.loss.item() * input_ids.size(1)

    return -neg_log_likelihood  # return positive log-likelihood

correct = 0
total = len(data)

for item in tqdm(data):
    question = item["question"]                          # string
    option_texts = item["choices"]["text"]               # list of strings
    option_labels = item["choices"]["label"]             # list of labels (A, B, C, D, E)
    gold_label = item["answerKey"]

    # compute likelihood for each option
    scores = []
    for opt in option_texts:
        score = option_loglikelihood(question, opt)
        scores.append(score)

    # pick the highest-likelihood option
    pred_idx = scores.index(max(scores))
    pred_label = option_labels[pred_idx]

    if pred_label == gold_label:
        correct += 1

accuracy = correct / total
accuracy

data[0]

print(f"GPT-2 Small Accuracy on CommonsenseQA (zero-shot): {accuracy*100:.2f}%")

import pandas as pd

results = []
for item in data:
    question = item["question"]
    option_texts = item["choices"]["text"]
    option_labels = item["choices"]["label"]
    gold_label = item["answerKey"]

    scores = [option_loglikelihood(question, opt) for opt in option_texts]
    pred_idx = scores.index(max(scores))
    pred_label = option_labels[pred_idx]

    results.append({
        "question": question,
        "gold": gold_label,
        "pred": pred_label,
        "scores": scores
    })

df = pd.DataFrame(results)
df.to_csv("gpt2_commonsenseqa_predictions.csv", index=False)

!ls -lh

import pandas as pd

# Example for CommonsenseQA
df.to_csv("gpt2_commonsense_qa_predictions.csv", index=False)
!ls -lh

from google.colab import files

files.download("gpt2_commonsense_qa_predictions.csv")







from datasets import load_dataset

# Choose "ARC Challenge" or "ARC Easy"
dataset = load_dataset("ai2_arc", "ARC-Challenge")  # or "ARC-Easy"
data = dataset["validation"]  # validation split has labels

print(data[0])

correct = 0
total = len(data)

for item in tqdm(data):
    question = item["question"]
    option_texts = item["choices"]      # already a list of strings
    gold_label = item["answerKey"]      # "A", "B", "C", "D"

    # generate labels "A","B",... if needed
    option_labels = ["A","B","C","D"][:len(option_texts)]

    # compute likelihood for each option
    scores = [option_loglikelihood(question, opt) for opt in option_texts]
    pred_idx = scores.index(max(scores))
    pred_label = option_labels[pred_idx]

    if pred_label == gold_label:
        correct += 1

accuracy = correct / total
print(f"GPT-2 Small Accuracy on ARC Challenge (zero-shot): {accuracy*100:.2f}%")

import pandas as pd
from tqdm import tqdm

results = []

for item in tqdm(data, desc="Creating ARC predictions CSV"):
    question = item["question"]
    option_texts = item["choices"]           # already a list of strings
    option_labels = ["A", "B", "C", "D"][:len(option_texts)]
    gold_label = item["answerKey"]

    # compute likelihoods
    scores = [option_loglikelihood(question, opt) for opt in option_texts]
    pred_idx = scores.index(max(scores))
    pred_label = option_labels[pred_idx]

    results.append({
        "question": question,
        "gold": gold_label,
        "pred": pred_label,
        "scores": scores,
        "options": option_texts,
        "labels": option_labels
    })

# save CSV
df = pd.DataFrame(results)
df.to_csv("gpt2_arc_challenge_predictions.csv", index=False)
print("Predictions saved to gpt2_arc_challenge_predictions.csv")

!zip -r gpt2_arc_challenge_predictions.zip gpt2_arc_challenge_predictions.csv

!ls -lh gpt2_arc_challenge_predictions.zip

from google.colab import files
files.download("gpt2_arc_challenge_predictions.zip")

